export const CHNAGE_GOODS_NUM = 'CHNAGE_GOODS_NUM'
export const GET_LOADING = "GET_LOADING"
export const GET_CART_LIST = "GET_CART_LIST"
export const CHECK_GOODS = 'CHECK_GOODS'
export const CHECK_ALL_GOODS = 'CHECK_ALL_GOODS'
export const CLEAR_GOODS = 'CLEAR_GOODS'